# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Multi-stage build for Kanta MCP Server

# Builder stage: install deps and compile TypeScript
FROM node:lts-alpine AS builder
WORKDIR /app

# Copy package files and tsconfig
COPY package.json package-lock.json tsconfig.json ./

# Copy source code
COPY src ./src
COPY api-docs.json .

# Install dependencies and build
RUN npm install && npm run build

# Production stage: only runtime deps and compiled code
FROM node:lts-alpine AS runtime
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install only production dependencies
RUN npm install --production

# Copy Smithery HTTP build output
COPY --from=builder /app/.smithery ./.smithery

# Default command to run the server (Smithery HTTP transport)
ENTRYPOINT ["node", ".smithery/index.cjs"]
